name: CI TaskManager

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Django dependencies
      working-directory: ./taskmanager
      run: |
        pip install -r requirements.txt

    - name: Criar .env para CI
      working-directory: ./taskmanager
      run: |
        echo "POSTGRES_DB=test_db" > .env
        echo "POSTGRES_USER=postgres" >> .env
        echo "POSTGRES_PASSWORD=postgres" >> .env
        echo "POSTGRES_HOST=localhost" >> .env
        echo "SECRET_KEY=dummy-key-for-ci" >> .env
        echo "DEBUG=False" >> .env

    - name: Run Django migrations
      working-directory: ./taskmanager
      run: |
        python manage.py migrate

    - name: Run Django tests
      working-directory: ./taskmanager
      run: |
        python manage.py test


  test-frontend:
    runs-on: ubuntu-latest
    needs: test-backend  # Só executa se o backend passar
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install React dependencies
      working-directory: ./frontend
      run: |
        npm install

    - name: Run React tests
      working-directory: ./frontend
      run: |
        npm test -- --watchAll=false

    - name: Build React app
      working-directory: ./frontend
      run: |
        npm run build