name: CI TaskManager

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_HOST: localhost
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SECRET_KEY: dummy-key-for-ci
      DEBUG: "False"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Django dependencies
      working-directory: ./taskmanager
      run: |
        pip install -r requirements.txt

    - name: Wait for PostgreSQL
      run: |
        for i in {1..10}; do
          if pg_isready -h localhost -p 5432 -U postgres -d test_db; then
            echo "PostgreSQL está pronto!"
            exit 0
          fi
          echo "Aguardando PostgreSQL... ($i/10)"
          sleep 5
        done
        echo "PostgreSQL não iniciou a tempo"
        exit 1

    - name: Apply migrations
      working-directory: ./taskmanager
      run: |
        python manage.py migrate

    - name: Run Django tests
      working-directory: ./taskmanager
      run: |
        python manage.py test

  test-frontend:
    runs-on: ubuntu-latest
    needs: test-backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install React dependencies
      working-directory: ./frontend
      run: |
        npm install

    - name: Run React tests
      working-directory: ./frontend
      run: |
        npm test -- --watchAll=false

    - name: Build React app
      working-directory: ./frontend
      run: |
        npm run build